// Code generated by protoc-gen-go. DO NOT EDIT.
// source: as/integration/integration.proto

package integration

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/sagar-patel-sls/chirpstack-api/go/v3/common"
	gw "github.com/sagar-patel-sls/chirpstack-api/go/v3/gw"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorType int32

const (
	// Unknown type.
	ErrorType_UNKNOWN ErrorType = 0
	// Error related to the downlink payload size.
	// Usually seen when the payload exceeded the maximum allowed payload size.
	ErrorType_DOWNLINK_PAYLOAD_SIZE ErrorType = 1
	// Error related to the downlink frame-counter.
	// Usually seen when the frame-counter has already been used.
	ErrorType_DOWNLINK_FCNT ErrorType = 2
	// Uplink codec error.
	ErrorType_UPLINK_CODEC ErrorType = 3
	// Downlink codec error.
	ErrorType_DOWNLINK_CODEC ErrorType = 4
	// OTAA error.
	ErrorType_OTAA ErrorType = 5
	// Uplink frame-counter was reset.
	ErrorType_UPLINK_FCNT_RESET ErrorType = 6
	// Uplink MIC error.
	ErrorType_UPLINK_MIC ErrorType = 7
	// Uplink frame-counter retransmission.
	ErrorType_UPLINK_FCNT_RETRANSMISSION ErrorType = 8
	// Downlink gateway error.
	ErrorType_DOWNLINK_GATEWAY ErrorType = 9
)

var ErrorType_name = map[int32]string{
	0: "UNKNOWN",
	1: "DOWNLINK_PAYLOAD_SIZE",
	2: "DOWNLINK_FCNT",
	3: "UPLINK_CODEC",
	4: "DOWNLINK_CODEC",
	5: "OTAA",
	6: "UPLINK_FCNT_RESET",
	7: "UPLINK_MIC",
	8: "UPLINK_FCNT_RETRANSMISSION",
	9: "DOWNLINK_GATEWAY",
}

var ErrorType_value = map[string]int32{
	"UNKNOWN":                    0,
	"DOWNLINK_PAYLOAD_SIZE":      1,
	"DOWNLINK_FCNT":              2,
	"UPLINK_CODEC":               3,
	"DOWNLINK_CODEC":             4,
	"OTAA":                       5,
	"UPLINK_FCNT_RESET":          6,
	"UPLINK_MIC":                 7,
	"UPLINK_FCNT_RETRANSMISSION": 8,
	"DOWNLINK_GATEWAY":           9,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}

func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{0}
}

// UplinkEvent is the message sent when an uplink payload has been received.
type UplinkEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Receiving gateway RX info.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,5,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,6,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Device has ADR bit set.
	Adr bool `protobuf:"varint,7,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,8,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frame counter.
	FCnt uint32 `protobuf:"varint,9,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,10,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// FRMPayload data.
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	// JSON string containing the decoded object.
	// Note that this is only set when a codec is configured in the Device Profile.
	ObjectJson string `protobuf:"bytes,12,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Uplink was of type confirmed.
	ConfirmedUplink bool `protobuf:"varint,14,opt,name=confirmed_uplink,json=confirmedUplink,proto3" json:"confirmed_uplink,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,15,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Published at timestamp.
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Device Profile UUID as string
	DeviceProfileId string `protobuf:"bytes,17,opt,name=device_profile_id,json=deviceProfileID,proto3" json:"device_profile_id,omitempty"`
	// Device Profile name
	DeviceProfileName string `protobuf:"bytes,18,opt,name=device_profile_name,json=deviceProfileName,proto3" json:"device_profile_name,omitempty"`
	// Time-on-air, calculated by the Application Server using payload size and
	// transmission settings
	ConsumedAirtime      *durationpb.Duration `protobuf:"bytes,19,opt,name=consumed_airtime,proto3" json:"consumed_airtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UplinkEvent) Reset()         { *m = UplinkEvent{} }
func (m *UplinkEvent) String() string { return proto.CompactTextString(m) }
func (*UplinkEvent) ProtoMessage()    {}
func (*UplinkEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{0}
}

func (m *UplinkEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UplinkEvent.Unmarshal(m, b)
}
func (m *UplinkEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UplinkEvent.Marshal(b, m, deterministic)
}
func (m *UplinkEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UplinkEvent.Merge(m, src)
}
func (m *UplinkEvent) XXX_Size() int {
	return xxx_messageInfo_UplinkEvent.Size(m)
}
func (m *UplinkEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UplinkEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UplinkEvent proto.InternalMessageInfo

func (m *UplinkEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *UplinkEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *UplinkEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *UplinkEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *UplinkEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

func (m *UplinkEvent) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *UplinkEvent) GetAdr() bool {
	if m != nil {
		return m.Adr
	}
	return false
}

func (m *UplinkEvent) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *UplinkEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *UplinkEvent) GetFPort() uint32 {
	if m != nil {
		return m.FPort
	}
	return 0
}

func (m *UplinkEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UplinkEvent) GetObjectJson() string {
	if m != nil {
		return m.ObjectJson
	}
	return ""
}

func (m *UplinkEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *UplinkEvent) GetConfirmedUplink() bool {
	if m != nil {
		return m.ConfirmedUplink
	}
	return false
}

func (m *UplinkEvent) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *UplinkEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

func (m *UplinkEvent) GetDeviceProfileId() string {
	if m != nil {
		return m.DeviceProfileId
	}
	return ""
}

func (m *UplinkEvent) GetDeviceProfileName() string {
	if m != nil {
		return m.DeviceProfileName
	}
	return ""
}

func (m *UplinkEvent) GetConsumedAirtime() *durationpb.Duration {
	if m != nil {
		return m.ConsumedAirtime
	}
	return nil
}

// JoinEvent is the message sent when a device joined the network.
// Note that this is only sent after the first received uplink after the
// device (re)activation.
type JoinEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,5,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Receiving gateway RX info.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,6,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,8,opt,name=dr,proto3" json:"dr,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *JoinEvent) Reset()         { *m = JoinEvent{} }
func (m *JoinEvent) String() string { return proto.CompactTextString(m) }
func (*JoinEvent) ProtoMessage()    {}
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{1}
}

func (m *JoinEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinEvent.Unmarshal(m, b)
}
func (m *JoinEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinEvent.Marshal(b, m, deterministic)
}
func (m *JoinEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinEvent.Merge(m, src)
}
func (m *JoinEvent) XXX_Size() int {
	return xxx_messageInfo_JoinEvent.Size(m)
}
func (m *JoinEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JoinEvent proto.InternalMessageInfo

func (m *JoinEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *JoinEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *JoinEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *JoinEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *JoinEvent) GetDevAddr() []byte {
	if m != nil {
		return m.DevAddr
	}
	return nil
}

func (m *JoinEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if m != nil {
		return m.RxInfo
	}
	return nil
}

func (m *JoinEvent) GetTxInfo() *gw.UplinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *JoinEvent) GetDr() uint32 {
	if m != nil {
		return m.Dr
	}
	return 0
}

func (m *JoinEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *JoinEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// AckEvent is the message sent when a confirmation on a confirmed downlink
// has been received -or- when the downlink timed out.
type AckEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Frame was acknowledged.
	Acknowledged bool `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Downlink frame counter to which the acknowledgement relates.
	FCnt uint32 `protobuf:"varint,6,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AckEvent) Reset()         { *m = AckEvent{} }
func (m *AckEvent) String() string { return proto.CompactTextString(m) }
func (*AckEvent) ProtoMessage()    {}
func (*AckEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{2}
}

func (m *AckEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckEvent.Unmarshal(m, b)
}
func (m *AckEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckEvent.Marshal(b, m, deterministic)
}
func (m *AckEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckEvent.Merge(m, src)
}
func (m *AckEvent) XXX_Size() int {
	return xxx_messageInfo_AckEvent.Size(m)
}
func (m *AckEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AckEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AckEvent proto.InternalMessageInfo

func (m *AckEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *AckEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *AckEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *AckEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *AckEvent) GetAcknowledged() bool {
	if m != nil {
		return m.Acknowledged
	}
	return false
}

func (m *AckEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *AckEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AckEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// TxAckEvent is the message sent when a downlink was acknowledged by the gateway
// for transmission. As a downlink can be scheduled in the future, this event
// does not confirm that the message has already been transmitted.
type TxAckEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,5,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,7,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// TX info.
	TxInfo *gw.DownlinkTXInfo `protobuf:"bytes,8,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TxAckEvent) Reset()         { *m = TxAckEvent{} }
func (m *TxAckEvent) String() string { return proto.CompactTextString(m) }
func (*TxAckEvent) ProtoMessage()    {}
func (*TxAckEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{3}
}

func (m *TxAckEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxAckEvent.Unmarshal(m, b)
}
func (m *TxAckEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxAckEvent.Marshal(b, m, deterministic)
}
func (m *TxAckEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxAckEvent.Merge(m, src)
}
func (m *TxAckEvent) XXX_Size() int {
	return xxx_messageInfo_TxAckEvent.Size(m)
}
func (m *TxAckEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TxAckEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TxAckEvent proto.InternalMessageInfo

func (m *TxAckEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *TxAckEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *TxAckEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *TxAckEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *TxAckEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *TxAckEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TxAckEvent) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *TxAckEvent) GetTxInfo() *gw.DownlinkTXInfo {
	if m != nil {
		return m.TxInfo
	}
	return nil
}

func (m *TxAckEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// ErrorEvent is the message sent when an error occurred.
type ErrorEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Error type.
	Type ErrorType `protobuf:"varint,5,opt,name=type,proto3,enum=integration.ErrorType" json:"type,omitempty"`
	// Error message.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Downlink frame-counter (in case the downlink is related to a scheduled downlink).
	FCnt uint32 `protobuf:"varint,7,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ErrorEvent) Reset()         { *m = ErrorEvent{} }
func (m *ErrorEvent) String() string { return proto.CompactTextString(m) }
func (*ErrorEvent) ProtoMessage()    {}
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{4}
}

func (m *ErrorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorEvent.Unmarshal(m, b)
}
func (m *ErrorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorEvent.Marshal(b, m, deterministic)
}
func (m *ErrorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorEvent.Merge(m, src)
}
func (m *ErrorEvent) XXX_Size() int {
	return xxx_messageInfo_ErrorEvent.Size(m)
}
func (m *ErrorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorEvent proto.InternalMessageInfo

func (m *ErrorEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *ErrorEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *ErrorEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *ErrorEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *ErrorEvent) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return ErrorType_UNKNOWN
}

func (m *ErrorEvent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ErrorEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *ErrorEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ErrorEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// StatusEvent is the message sent when a device-status mac-command was sent
// by the device.
type StatusEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// The demodulation signal-to-noise ratio in dB for the last successfully
	// received device-status request by the Network Server.
	Margin int32 `protobuf:"varint,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Device is connected to an external power source.
	ExternalPowerSource bool `protobuf:"varint,6,opt,name=external_power_source,json=externalPowerSource,proto3" json:"external_power_source,omitempty"`
	// Battery level is not available.
	BatteryLevelUnavailable bool `protobuf:"varint,7,opt,name=battery_level_unavailable,json=batteryLevelUnavailable,proto3" json:"battery_level_unavailable,omitempty"`
	// Battery level.
	BatteryLevel float32 `protobuf:"fixed32,8,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusEvent) Reset()         { *m = StatusEvent{} }
func (m *StatusEvent) String() string { return proto.CompactTextString(m) }
func (*StatusEvent) ProtoMessage()    {}
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{5}
}

func (m *StatusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusEvent.Unmarshal(m, b)
}
func (m *StatusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusEvent.Marshal(b, m, deterministic)
}
func (m *StatusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusEvent.Merge(m, src)
}
func (m *StatusEvent) XXX_Size() int {
	return xxx_messageInfo_StatusEvent.Size(m)
}
func (m *StatusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StatusEvent proto.InternalMessageInfo

func (m *StatusEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *StatusEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *StatusEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *StatusEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *StatusEvent) GetMargin() int32 {
	if m != nil {
		return m.Margin
	}
	return 0
}

func (m *StatusEvent) GetExternalPowerSource() bool {
	if m != nil {
		return m.ExternalPowerSource
	}
	return false
}

func (m *StatusEvent) GetBatteryLevelUnavailable() bool {
	if m != nil {
		return m.BatteryLevelUnavailable
	}
	return false
}

func (m *StatusEvent) GetBatteryLevel() float32 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *StatusEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StatusEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// LocationEvent is the message sent when a geolocation resolve was returned.
type LocationEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Uplink IDs used for geolocation.
	// This is set in case the geolocation is based on the uplink meta-data.
	UplinkIds [][]byte `protobuf:"bytes,7,rep,name=uplink_ids,json=uplinkIDs,proto3" json:"uplink_ids,omitempty"`
	// Frame counter (in case the geolocation is based on the payload).
	// This is set in case the geolocation is based on the uplink payload content.
	FCnt uint32 `protobuf:"varint,8,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LocationEvent) Reset()         { *m = LocationEvent{} }
func (m *LocationEvent) String() string { return proto.CompactTextString(m) }
func (*LocationEvent) ProtoMessage()    {}
func (*LocationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{6}
}

func (m *LocationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationEvent.Unmarshal(m, b)
}
func (m *LocationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationEvent.Marshal(b, m, deterministic)
}
func (m *LocationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationEvent.Merge(m, src)
}
func (m *LocationEvent) XXX_Size() int {
	return xxx_messageInfo_LocationEvent.Size(m)
}
func (m *LocationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LocationEvent proto.InternalMessageInfo

func (m *LocationEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *LocationEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *LocationEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *LocationEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *LocationEvent) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LocationEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *LocationEvent) GetUplinkIds() [][]byte {
	if m != nil {
		return m.UplinkIds
	}
	return nil
}

func (m *LocationEvent) GetFCnt() uint32 {
	if m != nil {
		return m.FCnt
	}
	return 0
}

func (m *LocationEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// IntegrationEvent is the message that can be sent by an integration.
// It allows for sending events which are provided by an external integration
// which are "not native" to ChirpStack.
type IntegrationEvent struct {
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Integration name.
	IntegrationName string `protobuf:"bytes,6,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	// Event type.
	EventType string `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// JSON string containing the event object.
	ObjectJson string `protobuf:"bytes,8,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// Published at timestamp.
	PublishedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IntegrationEvent) Reset()         { *m = IntegrationEvent{} }
func (m *IntegrationEvent) String() string { return proto.CompactTextString(m) }
func (*IntegrationEvent) ProtoMessage()    {}
func (*IntegrationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{7}
}

func (m *IntegrationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationEvent.Unmarshal(m, b)
}
func (m *IntegrationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationEvent.Marshal(b, m, deterministic)
}
func (m *IntegrationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationEvent.Merge(m, src)
}
func (m *IntegrationEvent) XXX_Size() int {
	return xxx_messageInfo_IntegrationEvent.Size(m)
}
func (m *IntegrationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationEvent proto.InternalMessageInfo

func (m *IntegrationEvent) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *IntegrationEvent) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *IntegrationEvent) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *IntegrationEvent) GetDevEui() []byte {
	if m != nil {
		return m.DevEui
	}
	return nil
}

func (m *IntegrationEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *IntegrationEvent) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func (m *IntegrationEvent) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *IntegrationEvent) GetObjectJson() string {
	if m != nil {
		return m.ObjectJson
	}
	return ""
}

func (m *IntegrationEvent) GetPublishedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.PublishedAt
	}
	return nil
}

// GatewayStatsEvent is the message sent gateway stats.
type GatewayStatsEvent struct {
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Gateway IP.
	Ip string `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	// Gateway time.
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Gateway location.
	Location *common.Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Gateway configuration version (this maps to the config_version sent
	// by LoRa Server to the gateway).
	ConfigVersion string `protobuf:"bytes,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Number of radio packets received.
	RxPacketsReceived uint32 `protobuf:"varint,5,opt,name=rx_packets_received,json=rxPacketsReceived,proto3" json:"rx_packets_received,omitempty"`
	// Number of radio packets received with valid PHY CRC.
	RxPacketsReceivedOk uint32 `protobuf:"varint,6,opt,name=rx_packets_received_ok,json=rxPacketsReceivedOK,proto3" json:"rx_packets_received_ok,omitempty"`
	// Number of downlink packets received for transmission.
	TxPacketsReceived uint32 `protobuf:"varint,7,opt,name=tx_packets_received,json=txPacketsReceived,proto3" json:"tx_packets_received,omitempty"`
	// Number of downlink packets emitted.
	TxPacketsEmitted uint32 `protobuf:"varint,8,opt,name=tx_packets_emitted,json=txPacketsEmitted,proto3" json:"tx_packets_emitted,omitempty"`
	// Additional gateway meta-data.
	MetaData map[string]string `protobuf:"bytes,10,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Stats ID (UUID).
	// Unique identifier for the gateway stats.
	StatsId []byte `protobuf:"bytes,11,opt,name=stats_id,json=statsID,proto3" json:"stats_id,omitempty"`
	// Tags (user defined).
	// These tags are exposed in the stat event payloads or to integration. Tags are
	// intended for aggregation and filtering.
	Tags                 map[string]string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GatewayStatsEvent) Reset()         { *m = GatewayStatsEvent{} }
func (m *GatewayStatsEvent) String() string { return proto.CompactTextString(m) }
func (*GatewayStatsEvent) ProtoMessage()    {}
func (*GatewayStatsEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{8}
}

func (m *GatewayStatsEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayStatsEvent.Unmarshal(m, b)
}
func (m *GatewayStatsEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayStatsEvent.Marshal(b, m, deterministic)
}
func (m *GatewayStatsEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayStatsEvent.Merge(m, src)
}
func (m *GatewayStatsEvent) XXX_Size() int {
	return xxx_messageInfo_GatewayStatsEvent.Size(m)
}
func (m *GatewayStatsEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayStatsEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayStatsEvent proto.InternalMessageInfo

func (m *GatewayStatsEvent) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *GatewayStatsEvent) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GatewayStatsEvent) GetTime() *timestamppb.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *GatewayStatsEvent) GetLocation() *common.Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GatewayStatsEvent) GetConfigVersion() string {
	if m != nil {
		return m.ConfigVersion
	}
	return ""
}

func (m *GatewayStatsEvent) GetRxPacketsReceived() uint32 {
	if m != nil {
		return m.RxPacketsReceived
	}
	return 0
}

func (m *GatewayStatsEvent) GetRxPacketsReceivedOk() uint32 {
	if m != nil {
		return m.RxPacketsReceivedOk
	}
	return 0
}

func (m *GatewayStatsEvent) GetTxPacketsReceived() uint32 {
	if m != nil {
		return m.TxPacketsReceived
	}
	return 0
}

func (m *GatewayStatsEvent) GetTxPacketsEmitted() uint32 {
	if m != nil {
		return m.TxPacketsEmitted
	}
	return 0
}

func (m *GatewayStatsEvent) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *GatewayStatsEvent) GetStatsId() []byte {
	if m != nil {
		return m.StatsId
	}
	return nil
}

func (m *GatewayStatsEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// GatewayConnStatEvent is the message sent gateway connection stats.
type GatewayConnStatEvent struct {
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Stat contains Gateway connection status ONLINE/OFFLINE
	State gw.State `protobuf:"varint,2,opt,name=state,proto3,enum=gw.State" json:"state,omitempty"`
	// Additional gateway meta-data.
	MetaData map[string]string `protobuf:"bytes,3,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Tags (user defined).
	// These tags are exposed in the stat event payloads or to integration. Tags are
	// intended for aggregation and filtering.
	Tags                 map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GatewayConnStatEvent) Reset()         { *m = GatewayConnStatEvent{} }
func (m *GatewayConnStatEvent) String() string { return proto.CompactTextString(m) }
func (*GatewayConnStatEvent) ProtoMessage()    {}
func (*GatewayConnStatEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ba82681be587591, []int{9}
}

func (m *GatewayConnStatEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayConnStatEvent.Unmarshal(m, b)
}
func (m *GatewayConnStatEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayConnStatEvent.Marshal(b, m, deterministic)
}
func (m *GatewayConnStatEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayConnStatEvent.Merge(m, src)
}
func (m *GatewayConnStatEvent) XXX_Size() int {
	return xxx_messageInfo_GatewayConnStatEvent.Size(m)
}
func (m *GatewayConnStatEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayConnStatEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayConnStatEvent proto.InternalMessageInfo

func (m *GatewayConnStatEvent) GetGatewayId() []byte {
	if m != nil {
		return m.GatewayId
	}
	return nil
}

func (m *GatewayConnStatEvent) GetState() gw.State {
	if m != nil {
		return m.State
	}
	return gw.State_OFFLINE
}

func (m *GatewayConnStatEvent) GetMetaData() map[string]string {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *GatewayConnStatEvent) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("integration.ErrorType", ErrorType_name, ErrorType_value)
	proto.RegisterType((*UplinkEvent)(nil), "integration.UplinkEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.UplinkEvent.TagsEntry")
	proto.RegisterType((*JoinEvent)(nil), "integration.JoinEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.JoinEvent.TagsEntry")
	proto.RegisterType((*AckEvent)(nil), "integration.AckEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.AckEvent.TagsEntry")
	proto.RegisterType((*TxAckEvent)(nil), "integration.TxAckEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.TxAckEvent.TagsEntry")
	proto.RegisterType((*ErrorEvent)(nil), "integration.ErrorEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.ErrorEvent.TagsEntry")
	proto.RegisterType((*StatusEvent)(nil), "integration.StatusEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.StatusEvent.TagsEntry")
	proto.RegisterType((*LocationEvent)(nil), "integration.LocationEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.LocationEvent.TagsEntry")
	proto.RegisterType((*IntegrationEvent)(nil), "integration.IntegrationEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.IntegrationEvent.TagsEntry")
	proto.RegisterType((*GatewayStatsEvent)(nil), "integration.GatewayStatsEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.GatewayStatsEvent.MetaDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "integration.GatewayStatsEvent.TagsEntry")
	proto.RegisterType((*GatewayConnStatEvent)(nil), "integration.GatewayConnStatEvent")
	proto.RegisterMapType((map[string]string)(nil), "integration.GatewayConnStatEvent.MetaDataEntry")
	proto.RegisterMapType((map[string]string)(nil), "integration.GatewayConnStatEvent.TagsEntry")
}

func init() {
	proto.RegisterFile("as/integration/integration.proto", fileDescriptor_5ba82681be587591)
}

var fileDescriptor_5ba82681be587591 = []byte{
	// 1489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xcb, 0x72, 0xdb, 0x46,
	0x16, 0x1d, 0xbe, 0x89, 0xcb, 0x87, 0xc0, 0x96, 0x65, 0x43, 0xaa, 0xb2, 0xc5, 0xd1, 0x8c, 0x6b,
	0xe4, 0x17, 0x59, 0x25, 0xcd, 0xc3, 0x65, 0xcf, 0xa3, 0x68, 0x91, 0xe3, 0xa2, 0x2d, 0x93, 0x2c,
	0x90, 0x8a, 0x63, 0x6f, 0x50, 0x2d, 0xa2, 0x09, 0xc3, 0x02, 0x01, 0x54, 0xa3, 0x49, 0x49, 0xdf,
	0x90, 0x7f, 0xc8, 0x2a, 0x8b, 0xec, 0xf2, 0x07, 0x59, 0xe6, 0x07, 0xb2, 0xcc, 0x7f, 0x64, 0x95,
	0x45, 0xaa, 0xbb, 0x21, 0x12, 0x20, 0x99, 0x92, 0xed, 0x85, 0xcd, 0x15, 0xd1, 0xb7, 0x0f, 0xd0,
	0xf7, 0x9e, 0x73, 0xef, 0xed, 0x6e, 0x42, 0x15, 0x07, 0x75, 0xdb, 0x65, 0xc4, 0xa2, 0x98, 0xd9,
	0x9e, 0x1b, 0x7d, 0xae, 0xf9, 0xd4, 0x63, 0x1e, 0x2a, 0x44, 0x4c, 0x3b, 0x9b, 0x43, 0x6f, 0x3c,
	0xf6, 0xdc, 0xba, 0xfc, 0x91, 0x88, 0x9d, 0x82, 0x75, 0x5e, 0xb7, 0xce, 0xc3, 0xc1, 0xae, 0xe5,
	0x79, 0x96, 0x43, 0xea, 0x62, 0x74, 0x3a, 0x19, 0xd5, 0x99, 0x3d, 0x26, 0x01, 0xc3, 0x63, 0x3f,
	0x04, 0xdc, 0x59, 0x04, 0x98, 0x93, 0xe8, 0x7a, 0x7b, 0xdf, 0x64, 0xa1, 0x70, 0xe2, 0x3b, 0xb6,
	0x7b, 0xd6, 0x9a, 0x12, 0x97, 0xa1, 0xbb, 0x50, 0xc6, 0xbe, 0xef, 0xd8, 0x43, 0x01, 0x32, 0x6c,
	0x53, 0x4b, 0x54, 0x13, 0xfb, 0x69, 0xbd, 0x14, 0xb1, 0xb6, 0x9b, 0xe8, 0x1e, 0xa8, 0x51, 0x98,
	0x8b, 0xc7, 0x44, 0x4b, 0x56, 0x13, 0xfb, 0x8a, 0xbe, 0x11, 0xb1, 0x77, 0xf0, 0x98, 0xa0, 0x5d,
	0x28, 0x98, 0x64, 0x6a, 0x0f, 0x89, 0x44, 0xa5, 0x04, 0x0a, 0xa4, 0x49, 0x00, 0x6e, 0x41, 0xce,
	0x24, 0x53, 0x83, 0x4c, 0x6c, 0x2d, 0x5d, 0x4d, 0xec, 0x17, 0xf5, 0xac, 0x49, 0xa6, 0xad, 0x93,
	0x36, 0xba, 0x07, 0x39, 0x7a, 0x61, 0xd8, 0xee, 0xc8, 0xd3, 0x32, 0xd5, 0xd4, 0x7e, 0xe1, 0x40,
	0xad, 0x59, 0xe7, 0x35, 0xe9, 0xad, 0xfe, 0x75, 0xdb, 0x1d, 0x79, 0x7a, 0x96, 0x5e, 0xf0, 0x5f,
	0x0e, 0x65, 0x21, 0x34, 0x5b, 0x4d, 0xc4, 0xa1, 0x83, 0x10, 0xca, 0x24, 0x54, 0x85, 0x14, 0x36,
	0xa9, 0x96, 0xab, 0x26, 0xf6, 0xf3, 0x3a, 0x7f, 0x44, 0x65, 0x48, 0x9a, 0x54, 0xcb, 0x57, 0x13,
	0xfb, 0x25, 0x3d, 0x69, 0x52, 0xb4, 0x09, 0x99, 0x91, 0x31, 0x74, 0x99, 0xa6, 0x08, 0x53, 0x7a,
	0x74, 0xe4, 0x32, 0xb4, 0x05, 0xd9, 0x91, 0xe1, 0x7b, 0x94, 0x69, 0x20, 0xac, 0x99, 0x51, 0xcf,
	0xa3, 0x0c, 0x21, 0x48, 0x9b, 0x98, 0x61, 0xad, 0x20, 0x3c, 0x17, 0xcf, 0x3c, 0x62, 0xef, 0xf4,
	0x3d, 0x19, 0x32, 0xe3, 0x7d, 0xe0, 0xb9, 0x5a, 0x51, 0x46, 0x2c, 0x4d, 0x2f, 0xfa, 0xdd, 0x0e,
	0xfa, 0x27, 0xa4, 0x19, 0xb6, 0x02, 0xad, 0x24, 0xa2, 0xda, 0xab, 0x45, 0xd3, 0x20, 0x22, 0x46,
	0x6d, 0x80, 0xad, 0xa0, 0xe5, 0x32, 0x7a, 0xa9, 0x0b, 0x3c, 0x67, 0x7d, 0xe8, 0xb9, 0x23, 0x9b,
	0x8e, 0x89, 0x69, 0x4c, 0x04, 0x50, 0x2b, 0x8b, 0x38, 0x36, 0x66, 0x76, 0xf9, 0x3e, 0xda, 0x86,
	0x3c, 0x27, 0x15, 0x9b, 0x26, 0xd5, 0x36, 0x84, 0x6f, 0x9c, 0xe4, 0x86, 0x69, 0x52, 0xf4, 0x1f,
	0x28, 0xfa, 0x93, 0x53, 0xc7, 0x0e, 0xde, 0x11, 0xd3, 0xc0, 0x4c, 0x53, 0x05, 0x61, 0x3b, 0x35,
	0x99, 0x29, 0xb5, 0xab, 0x4c, 0xa9, 0x0d, 0xae, 0x52, 0x49, 0x2f, 0xcc, 0xf0, 0x0d, 0x86, 0xee,
	0x43, 0x25, 0xd4, 0xd3, 0xa7, 0xde, 0xc8, 0x76, 0x08, 0x4f, 0x92, 0x8a, 0xd4, 0x5e, 0x4e, 0xf4,
	0xa4, 0xbd, 0xdd, 0x44, 0x35, 0xd8, 0x5c, 0xc0, 0x8a, 0x1c, 0x40, 0x02, 0x5d, 0x89, 0xa1, 0x45,
	0x2a, 0xb4, 0x44, 0x80, 0xc1, 0x84, 0xc7, 0x87, 0x6d, 0xca, 0x93, 0x59, 0xdb, 0x14, 0xee, 0x6d,
	0x2f, 0xb9, 0xd7, 0x0c, 0x13, 0x59, 0x5f, 0x7a, 0x65, 0xe7, 0x5f, 0xa0, 0xcc, 0xa8, 0xe3, 0x7a,
	0x9f, 0x91, 0x4b, 0x91, 0xc6, 0x8a, 0xce, 0x1f, 0xd1, 0x0d, 0xc8, 0x4c, 0xb1, 0x33, 0xb9, 0xca,
	0x58, 0x39, 0x78, 0x92, 0x7c, 0x9c, 0xd8, 0xfb, 0x29, 0x05, 0xca, 0x0b, 0xcf, 0x76, 0xd7, 0xaf,
	0x16, 0xa2, 0x7a, 0x66, 0xe2, 0x7a, 0x46, 0xca, 0x24, 0xfb, 0xe1, 0x65, 0x92, 0xbb, 0xa6, 0x4c,
	0x16, 0x8b, 0xe2, 0xef, 0x61, 0xce, 0x2a, 0x62, 0x89, 0x6a, 0x2c, 0x67, 0x67, 0x94, 0x2d, 0x65,
	0xec, 0x62, 0xae, 0xc1, 0x47, 0xe5, 0xda, 0xa7, 0x0b, 0xf9, 0x5b, 0x12, 0xf2, 0x8d, 0xe1, 0x1a,
	0xf6, 0xb4, 0x3d, 0x28, 0xe2, 0xe1, 0x99, 0xeb, 0x9d, 0x3b, 0xc4, 0xb4, 0x88, 0x29, 0xb4, 0xcc,
	0xeb, 0x31, 0xdb, 0xbc, 0xff, 0x64, 0x23, 0xfd, 0xe7, 0x30, 0xe4, 0x3f, 0x27, 0xf8, 0xdf, 0x8d,
	0xf1, 0x7f, 0x15, 0xe9, 0xb5, 0xf4, 0xe7, 0x3f, 0x13, 0xfd, 0xdf, 0xa7, 0x00, 0x06, 0x17, 0x6b,
	0x29, 0xc0, 0x8c, 0xdc, 0x4c, 0x84, 0xdc, 0x7f, 0x84, 0xe4, 0xca, 0xfa, 0xf9, 0x73, 0x8c, 0xdc,
	0x79, 0x1c, 0x4b, 0xf4, 0xde, 0x06, 0xb0, 0x30, 0x23, 0xe7, 0xf8, 0x92, 0xc7, 0x94, 0x13, 0xeb,
	0x28, 0xa1, 0xa5, 0xdd, 0x44, 0x0f, 0xe6, 0xd5, 0x26, 0x89, 0x47, 0xbc, 0xda, 0x9a, 0xde, 0xb9,
	0xbb, 0xa2, 0xde, 0x16, 0xa5, 0x52, 0x3e, 0x93, 0x54, 0xdf, 0xa6, 0x00, 0x5a, 0x94, 0x7a, 0x74,
	0xfd, 0xa4, 0xba, 0x0f, 0x69, 0x76, 0xe9, 0x13, 0xa1, 0x54, 0xf9, 0xe0, 0x66, 0x4c, 0x15, 0xe1,
	0xf2, 0xe0, 0xd2, 0x27, 0xba, 0xc0, 0xf0, 0x00, 0x09, 0x37, 0x89, 0x9a, 0x51, 0x74, 0x39, 0x98,
	0x8b, 0x9d, 0x5b, 0x21, 0x76, 0x7e, 0x85, 0xd8, 0x73, 0x26, 0xae, 0xad, 0xa5, 0xcf, 0x25, 0xd0,
	0xaf, 0x29, 0x28, 0xf4, 0x19, 0x66, 0x93, 0x60, 0xfd, 0x14, 0xba, 0x09, 0xd9, 0x31, 0xa6, 0x96,
	0xed, 0x0a, 0x8d, 0x32, 0x7a, 0x38, 0x42, 0x07, 0xb0, 0x45, 0x2e, 0x18, 0xa1, 0x2e, 0x76, 0x0c,
	0xdf, 0x3b, 0x27, 0xd4, 0x08, 0xbc, 0x09, 0x1d, 0x12, 0xa1, 0x4e, 0x5e, 0xdf, 0xbc, 0x9a, 0xec,
	0xf1, 0xb9, 0xbe, 0x98, 0x42, 0x4f, 0x60, 0xfb, 0x14, 0x33, 0x46, 0xe8, 0xa5, 0xe1, 0x90, 0x29,
	0x71, 0x8c, 0x89, 0x8b, 0xa7, 0xd8, 0x76, 0xf0, 0xa9, 0x43, 0xc2, 0xd3, 0xda, 0xad, 0x10, 0x70,
	0xcc, 0xe7, 0x4f, 0xe6, 0xd3, 0xe8, 0x2f, 0x50, 0x8a, 0xbd, 0x2b, 0xea, 0x2d, 0xa9, 0x17, 0xa3,
	0xf8, 0xd9, 0xa9, 0x4b, 0x59, 0x71, 0xea, 0x8a, 0x10, 0xbc, 0x36, 0x7b, 0xd8, 0x0f, 0x29, 0x28,
	0x1d, 0x7b, 0x52, 0xa7, 0xf5, 0x93, 0xfe, 0x21, 0xe4, 0x9d, 0xd0, 0x39, 0x21, 0x3e, 0x3f, 0x4b,
	0x84, 0xf7, 0x94, 0x2b, 0xa7, 0xf5, 0x19, 0x02, 0x3d, 0x8e, 0x35, 0xd8, 0xbf, 0xc6, 0xb8, 0x8f,
	0xc5, 0xb8, 0xaa, 0xc7, 0xca, 0x93, 0xae, 0x61, 0x9b, 0x72, 0xf7, 0x2b, 0xea, 0x8a, 0xb4, 0xb4,
	0x9b, 0xc1, 0xbc, 0xc2, 0xf3, 0x91, 0x0a, 0xff, 0x52, 0xa5, 0xfa, 0x63, 0x0a, 0xd4, 0xf6, 0x3c,
	0xb2, 0xf5, 0x13, 0xed, 0x69, 0x28, 0x83, 0xbc, 0x4e, 0xfd, 0x2d, 0x26, 0xc3, 0xa2, 0xe3, 0xab,
	0x6e, 0x1f, 0x11, 0xbc, 0x5c, 0x5b, 0x76, 0xdb, 0x8d, 0x88, 0x5d, 0x38, 0x70, 0x1b, 0x80, 0xf0,
	0x6f, 0x18, 0xa2, 0x7f, 0xe7, 0x04, 0x48, 0x11, 0x16, 0xde, 0xb2, 0x17, 0x2f, 0x48, 0xf9, 0xa5,
	0x0b, 0xd2, 0x97, 0x12, 0xf0, 0xbb, 0x0c, 0x54, 0x9e, 0xcb, 0xfd, 0x9b, 0x77, 0x84, 0xb0, 0xe3,
	0xc6, 0xb7, 0xf9, 0xc4, 0xe2, 0x36, 0x5f, 0x86, 0xa4, 0xed, 0x0b, 0x17, 0x15, 0x3d, 0x69, 0xfb,
	0xa8, 0x06, 0x69, 0x71, 0x71, 0x49, 0x5e, 0xeb, 0xb4, 0xc0, 0xc5, 0x2a, 0x29, 0x75, 0x6d, 0x25,
	0xdd, 0x85, 0xb2, 0xb8, 0xeb, 0x59, 0xc6, 0x94, 0xd0, 0x80, 0xbf, 0x93, 0x16, 0x2b, 0x97, 0xa4,
	0xf5, 0x2b, 0x69, 0xe4, 0x37, 0x2f, 0x7a, 0x61, 0xf8, 0x78, 0x78, 0x46, 0x58, 0x60, 0x50, 0x32,
	0x24, 0xf6, 0x34, 0x3c, 0x6e, 0x96, 0xf4, 0x0a, 0xbd, 0xe8, 0xc9, 0x19, 0x3d, 0x9c, 0x40, 0x87,
	0x70, 0x73, 0x05, 0xde, 0xf0, 0xce, 0xc2, 0x43, 0xe8, 0xe6, 0xd2, 0x2b, 0xdd, 0x97, 0x7c, 0x11,
	0xb6, 0x62, 0x11, 0xb9, 0xd9, 0x56, 0xd8, 0xd2, 0x22, 0x0f, 0x01, 0x45, 0xf0, 0x64, 0x6c, 0x33,
	0x46, 0xcc, 0xb0, 0x72, 0xd5, 0x19, 0xbc, 0x25, 0xed, 0xa8, 0x0d, 0xca, 0x98, 0x30, 0x6c, 0x88,
	0xfb, 0x35, 0x88, 0x8c, 0x7d, 0x18, 0xcb, 0xd8, 0x25, 0xa5, 0x6a, 0xaf, 0x08, 0xc3, 0x4d, 0xcc,
	0xb0, 0x4c, 0xdb, 0xfc, 0x38, 0x1c, 0xf2, 0xdb, 0x53, 0xc0, 0x51, 0x5c, 0x3f, 0x79, 0x53, 0xcf,
	0x89, 0x71, 0xbb, 0x89, 0xfe, 0x1d, 0x96, 0x44, 0x51, 0x2c, 0xb0, 0x7f, 0xcd, 0x02, 0x0b, 0x35,
	0xb1, 0xf3, 0x14, 0x4a, 0xb1, 0x35, 0x3f, 0x26, 0xdb, 0x3e, 0x3d, 0x4d, 0x7f, 0x49, 0xc2, 0x8d,
	0xd0, 0xb7, 0x23, 0xcf, 0x75, 0xb9, 0x7f, 0x1f, 0x94, 0xa9, 0xbb, 0x90, 0xe1, 0x61, 0xcb, 0x2f,
	0x96, 0x0f, 0x14, 0x7e, 0x1c, 0xe5, 0x2f, 0x13, 0x5d, 0xda, 0xd1, 0x71, 0x94, 0xf2, 0x94, 0x60,
	0xa4, 0xbe, 0x8a, 0x91, 0xd8, 0xaa, 0x7f, 0xc8, 0xfa, 0xff, 0x42, 0x6a, 0xd3, 0xe2, 0x43, 0x0f,
	0xae, 0xff, 0xd0, 0x5a, 0xb0, 0x7b, 0xff, 0xe7, 0x04, 0x28, 0xb3, 0xe3, 0x25, 0x2a, 0x40, 0xee,
	0xa4, 0xf3, 0xb2, 0xd3, 0x7d, 0xdd, 0x51, 0xff, 0x84, 0xb6, 0x61, 0xab, 0xd9, 0x7d, 0xdd, 0x39,
	0x6e, 0x77, 0x5e, 0x1a, 0xbd, 0xc6, 0x9b, 0xe3, 0x6e, 0xa3, 0x69, 0xf4, 0xdb, 0x6f, 0x5b, 0x6a,
	0x02, 0x55, 0xa0, 0x34, 0x9b, 0xfa, 0xff, 0x51, 0x67, 0xa0, 0x26, 0x91, 0x0a, 0xc5, 0x93, 0x9e,
	0x30, 0x1c, 0x75, 0x9b, 0xad, 0x23, 0x35, 0x85, 0x10, 0x94, 0x67, 0x20, 0x69, 0x4b, 0xa3, 0x3c,
	0xa4, 0xbb, 0x83, 0x46, 0x43, 0xcd, 0xa0, 0x2d, 0xa8, 0x84, 0x78, 0xfe, 0x01, 0x43, 0x6f, 0xf5,
	0x5b, 0x03, 0x35, 0x8b, 0xca, 0x00, 0xa1, 0xf9, 0x55, 0xfb, 0x48, 0xcd, 0xa1, 0x3b, 0xb0, 0x13,
	0x87, 0x0d, 0xf4, 0x46, 0xa7, 0xff, 0xaa, 0xdd, 0xef, 0xb7, 0xbb, 0x1d, 0x35, 0x8f, 0x6e, 0x80,
	0x3a, 0x5b, 0xe4, 0x79, 0x63, 0xd0, 0x7a, 0xdd, 0x78, 0xa3, 0x2a, 0xcf, 0xa6, 0x50, 0xb5, 0xbd,
	0xda, 0xf0, 0x9d, 0x4d, 0xfd, 0x80, 0xe1, 0xe1, 0x59, 0x0d, 0xfb, 0x76, 0x0d, 0x07, 0x51, 0x51,
	0x9e, 0x45, 0x37, 0xaf, 0x1e, 0x6f, 0x57, 0xbd, 0xc4, 0xdb, 0xff, 0x5a, 0x36, 0x7b, 0x37, 0x39,
	0xe5, 0x1d, 0xa9, 0x1e, 0x60, 0x0b, 0xd3, 0x47, 0x3e, 0x66, 0xc4, 0x79, 0x14, 0x38, 0x41, 0x7d,
	0xfe, 0xb5, 0x47, 0xd8, 0xb7, 0xeb, 0x96, 0x57, 0x9f, 0x1e, 0xd6, 0xe3, 0x7f, 0x71, 0x9e, 0x66,
	0x45, 0xdf, 0x3b, 0xfc, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x23, 0xfc, 0x4b, 0xfb, 0x14, 0x00,
	0x00,
}
